// AI Model Database — curated from Artificial Analysis & public benchmarks
// intelligenceScore: Artificial Analysis Intelligence Index (0–100)
// speed: output tokens/sec (first-party API median)
// inputPrice / outputPrice: USD per million tokens
// contextWindow: max tokens

let MODELS = [
  {
    id: "gpt-4o",
    curated: true, name: "GPT-4o",
    provider: "OpenAI",
    family: "GPT-4",
    tasks: ["text", "code", "vision", "audio", "agents", "rag"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 2.50,
    outputPrice: 10.00,
    blendedPrice: 5.00,
    speed: 68,
    latency: 500,
    platforms: [{"name": "Azure OpenAI", "regions": ["eastus", "southcentralus"]}, {"name": "OpenAI API"}],
    intelligenceScore: 79,
    supportsFinetuning: true,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "OpenAI's flagship multimodal model. Excels at reasoning, vision, coding and complex agentic tasks.",
    tags: ["multimodal", "flagship", "vision", "audio", "fine-tuning"],
    link: "https://platform.openai.com/docs/models/gpt-4o",
    releaseYear: 2024
  },
  {
    id: "gpt-4o-mini",
    curated: true, name: "GPT-4o mini",
    provider: "OpenAI",
    family: "GPT-4",
    tasks: ["text", "code", "vision", "rag"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 0.15,
    outputPrice: 0.60,
    blendedPrice: 0.30,
    speed: 105,
    latency: 500,
    platforms: [{"name": "Azure OpenAI", "regions": ["eastus", "southcentralus"]}, {"name": "OpenAI API"}],
    intelligenceScore: 58,
    supportsFinetuning: true,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Cost-optimized small model. Great for high-volume, lower-complexity tasks with vision support.",
    tags: ["cheap", "fast", "vision", "fine-tuning", "high-volume"],
    link: "https://platform.openai.com/docs/models/gpt-4o-mini",
    releaseYear: 2024
  },
  {
    id: "o1",
    curated: true, name: "o1",
    provider: "OpenAI",
    family: "o-series",
    tasks: ["text", "code", "reasoning", "agents"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 15.00,
    outputPrice: 60.00,
    blendedPrice: 30.00,
    speed: 28,
    latency: 500,
    platforms: [{"name": "Azure OpenAI", "regions": ["eastus"]}, {"name": "OpenAI API"}],
    intelligenceScore: 86,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Extended thinking model for complex scientific, math and coding problems. Slower but highly accurate.",
    tags: ["reasoning", "math", "science", "coding", "slow-but-smart"],
    link: "https://platform.openai.com/docs/models/o1",
    releaseYear: 2024
  },
  {
    id: "o3-mini",
    curated: true, name: "o3-mini",
    provider: "OpenAI",
    family: "o-series",
    tasks: ["text", "code", "reasoning"],
    openSource: false,
    contextWindow: 200000,
    inputPrice: 1.10,
    outputPrice: 4.40,
    blendedPrice: 2.20,
    speed: 55,
    latency: 500,
    platforms: [{"name": "Azure OpenAI", "regions": ["eastus"]}, {"name": "OpenAI API"}],
    intelligenceScore: 82,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Efficient reasoning model. Excellent coding and STEM performance at a fraction of o1 cost.",
    tags: ["reasoning", "coding", "math", "affordable"],
    link: "https://platform.openai.com/docs/models/o3-mini",
    releaseYear: 2025
  },
  {
    id: "claude-35-sonnet",
    curated: true, name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    family: "Claude 3.5",
    tasks: ["text", "code", "vision", "agents", "rag"],
    openSource: false,
    contextWindow: 200000,
    inputPrice: 3.00,
    outputPrice: 15.00,
    blendedPrice: 7.00,
    speed: 65,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "GCP Vertex AI", "regions": ["us-central1"]}, {"name": "Anthropic API"}],
    intelligenceScore: 78,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Anthropic's best everyday model. Top-tier coding, strong instruction following and long-context reasoning.",
    tags: ["coding", "instruction-following", "long-context", "vision"],
    link: "https://www.anthropic.com/claude/sonnet",
    releaseYear: 2024
  },
  {
    id: "claude-3-haiku",
    curated: true, name: "Claude 3 Haiku",
    provider: "Anthropic",
    family: "Claude 3",
    tasks: ["text", "code", "vision", "rag"],
    openSource: false,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    blendedPrice: 0.60,
    speed: 110,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "GCP Vertex AI", "regions": ["us-central1"]}, {"name": "Anthropic API"}],
    intelligenceScore: 54,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Anthropic's fastest and most affordable model. Ideal for real-time summarization and data extraction.",
    tags: ["fast", "cheap", "vision", "high-volume"],
    link: "https://www.anthropic.com/claude/haiku",
    releaseYear: 2024
  },
  {
    id: "claude-3-opus",
    curated: true, name: "Claude 3 Opus",
    provider: "Anthropic",
    family: "Claude 3",
    tasks: ["text", "code", "vision", "agents", "reasoning"],
    openSource: false,
    contextWindow: 200000,
    inputPrice: 15.00,
    outputPrice: 75.00,
    blendedPrice: 36.00,
    speed: 20,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "GCP Vertex AI", "regions": ["us-central1"]}, {"name": "Anthropic API"}],
    intelligenceScore: 74,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Anthropic's most powerful model. Exceptional for nuanced tasks requiring deep understanding.",
    tags: ["flagship", "nuanced", "long-context", "vision"],
    link: "https://www.anthropic.com/claude/opus",
    releaseYear: 2024
  },
  {
    id: "gemini-15-pro",
    curated: true, name: "Gemini 1.5 Pro",
    provider: "Google",
    family: "Gemini 1.5",
    tasks: ["text", "code", "vision", "audio", "rag", "agents"],
    openSource: false,
    contextWindow: 1000000,
    inputPrice: 1.25,
    outputPrice: 5.00,
    blendedPrice: 2.50,
    speed: 60,
    latency: 500,
    platforms: [{"name": "GCP Vertex AI", "regions": ["us-central1", "europe-west4"]}, {"name": "Google AI Studio"}],
    intelligenceScore: 72,
    supportsFinetuning: true,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Google's long-context powerhouse. Best-in-class for processing entire codebases, books or hours of video.",
    tags: ["1M-context", "multimodal", "video", "audio", "long-context"],
    link: "https://deepmind.google/technologies/gemini/pro/",
    releaseYear: 2024
  },
  {
    id: "gemini-15-flash",
    curated: true, name: "Gemini 1.5 Flash",
    provider: "Google",
    family: "Gemini 1.5",
    tasks: ["text", "code", "vision", "audio", "rag"],
    openSource: false,
    contextWindow: 1000000,
    inputPrice: 0.075,
    outputPrice: 0.30,
    blendedPrice: 0.15,
    speed: 150,
    latency: 500,
    platforms: [{"name": "GCP Vertex AI", "regions": ["us-central1", "europe-west4"]}, {"name": "Google AI Studio"}],
    intelligenceScore: 63,
    supportsFinetuning: true,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Ultra-fast, ultra-cheap multimodal model. Best price-performance for high-volume production workloads.",
    tags: ["fastest", "cheapest", "1M-context", "multimodal", "high-volume"],
    link: "https://deepmind.google/technologies/gemini/flash/",
    releaseYear: 2024
  },
  {
    id: "gemini-20-flash",
    curated: true, name: "Gemini 2.0 Flash",
    provider: "Google",
    family: "Gemini 2.0",
    tasks: ["text", "code", "vision", "audio", "agents", "rag"],
    openSource: false,
    contextWindow: 1000000,
    inputPrice: 0.10,
    outputPrice: 0.40,
    blendedPrice: 0.20,
    speed: 180,
    latency: 500,
    platforms: [{"name": "GCP Vertex AI", "regions": ["us-central1", "europe-west4"]}, {"name": "Google AI Studio"}],
    intelligenceScore: 70,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Next-gen fast model with native image generation and agentic capabilities. Excellent all-rounder.",
    tags: ["fast", "agentic", "multimodal", "image-gen", "1M-context"],
    link: "https://deepmind.google/technologies/gemini/",
    releaseYear: 2025
  },
  {
    id: "llama-3-70b",
    curated: true, name: "Llama 3.1 70B",
    provider: "Meta",
    family: "Llama 3",
    tasks: ["text", "code", "agents", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.52,
    outputPrice: 0.75,
    blendedPrice: 0.60,
    speed: 95,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "Azure AI", "regions": ["eastus2"]}, {"name": "Together AI"}],
    intelligenceScore: 68,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "llama",
    description: "Meta's flagship open-weights model. State-of-the-art open-source performance, great for self-hosting.",
    tags: ["open-source", "self-hosted", "fine-tuning", "privacy"],
    link: "https://llama.meta.com/",
    releaseYear: 2024
  },
  {
    id: "llama-3-8b",
    curated: true, name: "Llama 3.1 8B",
    provider: "Meta",
    family: "Llama 3",
    tasks: ["text", "code", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.05,
    outputPrice: 0.08,
    blendedPrice: 0.06,
    speed: 175,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "Azure AI", "regions": ["eastus2"]}, {"name": "Together AI"}],
    intelligenceScore: 46,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted", "on-device"],
    license: "llama",
    description: "Compact open model runnable on consumer hardware. Perfect for on-device deployment and fine-tuning experiments.",
    tags: ["open-source", "on-device", "self-hosted", "fine-tuning", "tiny"],
    link: "https://llama.meta.com/",
    releaseYear: 2024
  },
  {
    id: "mistral-large",
    curated: true, name: "Mistral Large",
    provider: "Mistral AI",
    family: "Mistral",
    tasks: ["text", "code", "agents", "rag"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 3.00,
    outputPrice: 9.00,
    blendedPrice: 5.00,
    speed: 42,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1"]}, {"name": "Mistral Platform"}],
    intelligenceScore: 67,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "proprietary",
    description: "Mistral's top model. Strong multilingual capabilities and function calling. European AI alternative.",
    tags: ["multilingual", "European", "function-calling"],
    link: "https://mistral.ai/",
    releaseYear: 2024
  },
  {
    id: "mistral-7b",
    curated: true, name: "Mistral 7B",
    provider: "Mistral AI",
    family: "Mistral",
    tasks: ["text", "code", "rag"],
    openSource: true,
    contextWindow: 32000,
    inputPrice: 0.07,
    outputPrice: 0.07,
    blendedPrice: 0.07,
    speed: 155,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1"]}, {"name": "Mistral Platform"}],
    intelligenceScore: 38,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted", "on-device"],
    license: "apache2",
    description: "Highly efficient open model punching above its weight. A go-to base for fine-tuning and edge deployment.",
    tags: ["open-source", "apache2", "fine-tuning", "self-hosted", "tiny"],
    link: "https://mistral.ai/",
    releaseYear: 2023
  },
  {
    id: "mixtral-8x7b",
    curated: true, name: "Mixtral 8x7B",
    provider: "Mistral AI",
    family: "Mixtral",
    tasks: ["text", "code", "rag", "agents"],
    openSource: true,
    contextWindow: 32000,
    inputPrice: 0.24,
    outputPrice: 0.24,
    blendedPrice: 0.24,
    speed: 120,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 56,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "apache2",
    description: "Mixture-of-experts open model. GPT-3.5-level quality at a fraction of the cost with fast inference.",
    tags: ["open-source", "MoE", "fast", "apache2", "cost-effective"],
    link: "https://mistral.ai/",
    releaseYear: 2024
  },
  {
    id: "deepseek-v3",
    curated: true, name: "DeepSeek V3",
    provider: "DeepSeek",
    family: "DeepSeek",
    tasks: ["text", "code", "reasoning", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.27,
    outputPrice: 1.10,
    blendedPrice: 0.55,
    speed: 50,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 75,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "mit",
    description: "Chinese frontier model matching GPT-4 class at a tiny fraction of the cost. Excellent reasoning.",
    tags: ["open-source", "mit", "best-value", "coding", "reasoning"],
    link: "https://www.deepseek.com/",
    releaseYear: 2024
  },
  {
    id: "deepseek-r1",
    curated: true, name: "DeepSeek R1",
    provider: "DeepSeek",
    family: "DeepSeek",
    tasks: ["text", "code", "reasoning", "math"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.55,
    outputPrice: 2.19,
    blendedPrice: 1.10,
    speed: 35,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 83,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "mit",
    description: "Open-source rival to o1. Extended chain-of-thought reasoning for math and science at low cost.",
    tags: ["open-source", "reasoning", "math", "science", "chain-of-thought"],
    link: "https://www.deepseek.com/",
    releaseYear: 2025
  },
  {
    id: "grok-2",
    curated: true, name: "Grok 2",
    provider: "xAI",
    family: "Grok",
    tasks: ["text", "code", "vision", "agents"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 2.00,
    outputPrice: 10.00,
    blendedPrice: 5.00,
    speed: 55,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 71,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "xAI's flagship model with real-time web access. Strong at current events and vision tasks.",
    tags: ["real-time", "web-search", "vision", "current-events"],
    link: "https://x.ai/",
    releaseYear: 2024
  },
  {
    id: "command-r-plus",
    curated: true, name: "Command R+",
    provider: "Cohere",
    family: "Command",
    tasks: ["text", "rag", "agents", "code"],
    openSource: false,
    contextWindow: 128000,
    inputPrice: 2.50,
    outputPrice: 10.00,
    blendedPrice: 5.00,
    speed: 65,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 60,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "proprietary",
    description: "Purpose-built for enterprise RAG and multi-step agents. Native grounded generation and citation support.",
    tags: ["RAG-specialist", "grounding", "citation", "enterprise", "agents"],
    link: "https://cohere.com/command",
    releaseYear: 2024
  },
  {
    id: "phi-3-medium",
    curated: true, name: "Phi-3 Medium",
    provider: "Microsoft",
    family: "Phi-3",
    tasks: ["text", "code", "reasoning"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.17,
    outputPrice: 0.68,
    blendedPrice: 0.35,
    speed: 90,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 55,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted", "on-device"],
    license: "mit",
    description: "Microsoft's small but capable model. Punches above its weight in reasoning and coding tasks.",
    tags: ["small", "efficient", "mit", "on-device", "fine-tuning"],
    link: "https://azure.microsoft.com/en-us/products/phi-3",
    releaseYear: 2024
  },
  {
    id: "phi-3-mini",
    curated: true, name: "Phi-3 Mini",
    provider: "Microsoft",
    family: "Phi-3",
    tasks: ["text", "code"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.04,
    outputPrice: 0.13,
    blendedPrice: 0.07,
    speed: 200,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 38,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted", "on-device"],
    license: "mit",
    description: "Tiny 3.8B model for edge and mobile. Best small model for on-device deployment with limited RAM.",
    tags: ["tiny", "on-device", "edge", "mobile", "mit"],
    link: "https://azure.microsoft.com/en-us/products/phi-3",
    releaseYear: 2024
  },
  {
    id: "qwen-25-72b",
    curated: true, name: "Qwen 2.5 72B",
    provider: "Alibaba",
    family: "Qwen",
    tasks: ["text", "code", "reasoning", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.40,
    outputPrice: 0.40,
    blendedPrice: 0.40,
    speed: 70,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 71,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "apache2",
    description: "Alibaba's powerful open model. Strong multilingual support and excellent math/coding performance.",
    tags: ["open-source", "multilingual", "coding", "math", "apache2"],
    link: "https://qwenlm.github.io/",
    releaseYear: 2024
  },
  {
    id: "gemma-2-9b",
    curated: true, name: "Gemma 2 9B",
    provider: "Google",
    family: "Gemma",
    tasks: ["text", "code", "rag"],
    openSource: true,
    contextWindow: 8192,
    inputPrice: 0.03,
    outputPrice: 0.06,
    blendedPrice: 0.04,
    speed: 160,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 44,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted", "on-device"],
    license: "apache2",
    description: "Google's efficient open model. Excellent quality/size ratio, great for fine-tuning and edge use.",
    tags: ["open-source", "google", "fine-tuning", "on-device", "apache2"],
    link: "https://ai.google.dev/gemma",
    releaseYear: 2024
  },
  {
    id: "claude-35-haiku",
    curated: true, name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    family: "Claude 3.5",
    tasks: ["text", "code", "vision", "rag", "agents"],
    openSource: false,
    contextWindow: 200000,
    inputPrice: 0.80,
    outputPrice: 4.00,
    blendedPrice: 2.00,
    speed: 90,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "GCP Vertex AI", "regions": ["us-central1"]}, {"name": "Anthropic API"}],
    intelligenceScore: 65,
    supportsFinetuning: false,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Fast, affordable Claude 3.5 class model. Strong coding and instruction following at lower cost.",
    tags: ["fast", "affordable", "coding", "vision", "instruction-following"],
    link: "https://www.anthropic.com/",
    releaseYear: 2024
  },
  {
    id: "llama-31-405b",
    curated: true, name: "Llama 3.1 405B",
    provider: "Meta",
    family: "Llama 3",
    tasks: ["text", "code", "agents", "reasoning", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 5.00,
    outputPrice: 5.00,
    blendedPrice: 5.00,
    speed: 30,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1", "us-west-2"]}, {"name": "Azure AI", "regions": ["eastus2"]}, {"name": "Together AI"}],
    intelligenceScore: 76,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "llama",
    description: "Meta's largest open model. GPT-4 class performance as an open-weights model you can host yourself.",
    tags: ["open-source", "flagship", "self-hosted", "GPT-4-class"],
    link: "https://llama.meta.com/",
    releaseYear: 2024
  },
  {
    id: "mistral-nemo",
    curated: true, name: "Mistral NeMo",
    provider: "Mistral AI",
    family: "Mistral",
    tasks: ["text", "code", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.13,
    outputPrice: 0.13,
    blendedPrice: 0.13,
    speed: 130,
    latency: 500,
    platforms: [{"name": "AWS Bedrock", "regions": ["us-east-1"]}, {"name": "Mistral Platform"}],
    intelligenceScore: 48,
    supportsFinetuning: true,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "apache2",
    description: "Drop-in replacement for Mistral 7B with 128K context. Great for multilingual apps on a budget.",
    tags: ["open-source", "multilingual", "apache2", "128K-context"],
    link: "https://mistral.ai/",
    releaseYear: 2024
  },
  {
    id: "deepseek-coder-v2",
    curated: true, name: "DeepSeek Coder V2",
    provider: "DeepSeek",
    family: "DeepSeek",
    tasks: ["code", "text", "rag"],
    openSource: true,
    contextWindow: 128000,
    inputPrice: 0.14,
    outputPrice: 0.28,
    blendedPrice: 0.20,
    speed: 60,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 70,
    supportsFinetuning: false,
    multimodal: false,
    deploymentOptions: ["api", "self-hosted"],
    license: "mit",
    description: "State-of-the-art open code model. Beats GPT-4 Turbo on many coding benchmarks at a fraction of the cost.",
    tags: ["code-specialist", "open-source", "mit", "best-value-coding"],
    link: "https://www.deepseek.com/",
    releaseYear: 2024
  },
  {
    id: "nova-pro",
    curated: true, name: "Nova Pro",
    provider: "Amazon",
    family: "Nova",
    tasks: ["text", "code", "vision", "rag", "agents"],
    openSource: false,
    contextWindow: 300000,
    inputPrice: 0.80,
    outputPrice: 3.20,
    blendedPrice: 1.60,
    speed: 70,
    latency: 500,
    platforms: [{"name": "OpenRouter"}],
    intelligenceScore: 68,
    supportsFinetuning: true,
    multimodal: true,
    deploymentOptions: ["api"],
    license: "proprietary",
    description: "Amazon's capable frontier model. Optimized for enterprise use on AWS Bedrock with fine-tuning support.",
    tags: ["AWS", "enterprise", "multimodal", "fine-tuning", "long-context"],
    link: "https://aws.amazon.com/bedrock/nova/",
    releaseYear: 2024
  }
];

// Provider color map
const PROVIDER_COLORS = {
  "OpenAI":     "#10a37f",
  "Anthropic":  "#d97706",
  "Google":     "#4285f4",
  "Meta":       "#0866ff",
  "Mistral AI": "#ff7000",
  "DeepSeek":   "#6b48ff",
  "xAI":        "#e2e8f0",
  "Cohere":     "#39d353",
  "Microsoft":  "#00a4ef",
  "Alibaba":    "#ff6a00",
  "Amazon":     "#ff9900"
};

// Task definitions
const TASKS = [
  { id: "text",      label: "Text Generation",    icon: "✍️",  desc: "Summarization, Q&A, writing, chat" },
  { id: "code",      label: "Coding",              icon: "💻",  desc: "Code generation, debugging, review" },
  { id: "vision",    label: "Vision / Image",      icon: "👁️",  desc: "Image understanding & description" },
  { id: "audio",     label: "Audio / Speech",      icon: "🎙️",  desc: "Transcription & audio analysis" },
  { id: "reasoning", label: "Complex Reasoning",   icon: "🧠",  desc: "Math, science, logic, research" },
  { id: "agents",    label: "Agents & Automation", icon: "🤖",  desc: "Multi-step tools, agentic pipelines" },
  { id: "rag",       label: "RAG / Search",         icon: "🔍",  desc: "Retrieval-augmented generation" },
  { id: "math",      label: "Math & Science",      icon: "🔬",  desc: "STEM reasoning and problem solving" }
];

